export const C = {
  bg:           "#f0f4f9",
  bgWhite:      "#ffffff",
  bgNavy:       "#0d1b35",
  bgBlue:       "#1a2e5a",
  bgLight:      "#e8eef6",

  primary:      "#1a6ed8",
  primaryDark:  "#0d4fa8",
  primaryLight: "#ebf2ff",

  accent:       "#c8a84b",
  accentLight:  "#fef9e7",

  text:         "#0d1b35",
  textWhite:    "#ffffff",
  muted:        "#5a6a85",
  sub:          "#8496b0",

  border:       "#d0dae8",
  borderDark:   "#b0bcd0",

  green:        "#1e7e34",
  greenLight:   "#e8f5e9",
  red:          "#c62828",
  redLight:     "#ffebee",
  yellow:       "#d97706",
  yellowLight:  "#fff7e6",

  gradient:     "linear-gradient(135deg, #0d1b35 0%, #1a2e5a 50%, #1a6ed8 100%)",
  gradientCard: "linear-gradient(135deg, #0d1b35, #1a2e5a)",
};

export const S = {
  card: {
    background: "#ffffff",
    border: "1px solid #d0dae8",
    borderRadius: 12,
    padding: 20,
    boxShadow: "0 2px 12px rgba(13,27,53,.08)",
  },
  input: {
    width: "100%",
    background: "#f0f4f9",
    border: "1.5px solid #d0dae8",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#0d1b35",
    fontSize: 14,
    fontFamily: "'Poppins', sans-serif",
    outline: "none",
    boxSizing: "border-box",
    marginBottom: 0,
  },
  label: {
    display: "block",
    color: "#5a6a85",
    fontSize: 11,
    fontWeight: 600,
    marginBottom: 5,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  btnPrimary: {
    background: "#1a6ed8",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "11px 22px",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
    fontFamily: "'Poppins', sans-serif",
    transition: "all .2s",
  },
  btnSecondary: {
    background: "transparent",
    color: "#5a6a85",
    border: "1.5px solid #d0dae8",
    borderRadius: 8,
    padding: "10px 18px",
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "'Poppins', sans-serif",
  },
  btnGreen: {
    background: "#1e7e34",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 20px",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "'Poppins', sans-serif",
  },
  btnDanger: {
    background: "#c62828",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 18px",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "'Poppins', sans-serif",
  },
  td: {
    padding: "10px 12px",
    borderBottom: "1px solid #d0dae8",
    color: "#0d1b35",
    fontSize: 13,
  },
  th: {
    padding: "10px 12px",
    textAlign: "left",
    color: "#5a6a85",
    borderBottom: "2px solid #d0dae8",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    background: "#f0f4f9",
  },
  badge: {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 10,
    fontSize: 11,
    fontWeight: 600,
  },
  alertOk: {
    background: "#e8f5e9",
    border: "1px solid #a5d6a7",
    color: "#1e7e34",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 14,
  },
  alertErr: {
    background: "#ffebee",
    border: "1px solid #ef9a9a",
    color: "#c62828",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 14,
  },
};

export const authPageStyles = {
  bg: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #0d1b35 0%, #1a2e5a 60%, #1a6ed8 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    fontFamily: "'Poppins', sans-serif",
  },
  card: {
    background: "#fff",
    border: "1px solid #d0dae8",
    borderRadius: 20,
    padding: "40px 36px",
    maxWidth: 440,
    width: "100%",
    boxShadow: "0 20px 60px rgba(13,27,53,.25)",
  },
  label: {
    display: "block",
    color: "#5a6a85",
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  input: {
    width: "100%",
    background: "#f0f4f9",
    border: "1.5px solid #d0dae8",
    borderRadius: 8,
    padding: "11px 14px",
    color: "#0d1b35",
    fontSize: 14,
    marginBottom: 14,
    boxSizing: "border-box",
    outline: "none",
    fontFamily: "'Poppins', sans-serif",
    transition: "border-color .2s",
  },
  btn: {
    width: "100%",
    background: "#1a6ed8",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "13px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    marginTop: 4,
    fontFamily: "'Poppins', sans-serif",
    letterSpacing: 0.3,
    transition: "background .2s",
  },
  title: {
    color: "#0d1b35",
    fontSize: 24,
    fontWeight: 800,
    textAlign: "center",
    margin: "0 0 4px",
    fontFamily: "'Montserrat', sans-serif",
  },
  sub: {
    color: "#5a6a85",
    fontSize: 13,
    textAlign: "center",
    margin: "0 0 28px",
  },
  error: {
    background: "#ffebee",
    border: "1px solid #ef9a9a",
    color: "#c62828",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 16,
    fontWeight: 500,
  },
  back: {
    color: "#5a6a85",
    fontSize: 13,
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginBottom: 24,
    fontWeight: 500,
  },
};
